export default {
  ADD_COMMAND: 'ADD_COMMAND',
  DEL_COMMAND: 'DEL_COMMAND',
  SAVE_COMMANDS: 'SAVE_COMMANDS',
  UPDATE_COMMAND: 'UPDATE_COMMAND',
  LOAD_PACKAGE: 'LOAD_PACKAGE',
  COMMAND: 'COMMAND',
  ACTION: 'ACTION',
  LOAD_PACKAGE: "LOAD_PACKAGE"
};
